Lint/PercentStringArray:
  Enabled: False

Metrics/LineLength:
  Max: 160

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: False

Style/ConditionalAssignment:
  Enabled: False

Style/Documentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

