AllCops:
  Exclude:
    - 'Rakefile'

Lint/PercentStringArray:
  Enabled: False

Metrics/LineLength:
  Max: 160

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: False

Style/ConditionalAssignment:
  Enabled: False

Style/Documentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/BlockDelimiters:
  Enabled: False

Layout/MultilineBlockLayout:
  Enabled: False

Style/WordArray:
  Enabled: False

Style/DoubleNegation:
  Enabled: False

Metrics/AbcSize:
  Enabled: False

Style/InverseMethods:
  Enabled: False

Style/IfUnlessModifier:
  Enabled: False
