language: ruby
sudo: false

rvm:
  - 2.3
  - 2.4
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

install:
  - bundle install

script:
  - bundle exec rake spec

notifications:
  email: false
